name: Run Detection Engine to detect REST interface changes

on:
  pull_request:
    branches:
      - master

jobs:
  run-container:
    runs-on: self-hosted

    steps:
      - name: Start Prebuilt Docker Container
        run: |
          docker run --rm --name detection_engine \
            -e REPO_OWNER=${{ github.repository_owner }} \
            -e REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2) \
            -e PR_NUMBER=${{ github.event.pull_request.number }} \
            -e PR_URL=${{ github.event.pull_request.html_url }} \
            -v ./data:/app/data \
            sms2sakthivel/adapt_detection_engine_github:latest

      - name: Verify Running Container
        run: docker ps -a
