name: Run Detection Engine to detect REST interface changes

on:
  pull_request:
    branches:
      - master

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
      - name: Start Prebuilt Docker Container
        run: |
          docker run --rm --name detection_engine \
            -e REPO_OWNER=${{ github.repository_owner }} \
            -e REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2) \
            -e PR_NUMBER=${{ github.event.pull_request.number }} \
            sms2sakthivel/adapt_detection_engine:latest

      - name: Verify Running Container
        run: docker ps -a
        
      - name: Save Logs as Artifact
        run: docker logs detection_engine > container_logs.txt

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: container-logs
          path: container_logs.txt
